### ISSUE TITLE
Exception when there are different remotes with the same URL

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/GitPullRequest#33]
This can happen when local branches reference the same remote URL using different remote names:

```
E:\code\roslyn> git pr --list

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key 'dotnet' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at GitPullRequest.Services.GitPullRequestService.FindPullRequests(IDictionary`2 gitRepositories, Branch branch) in C:\Source\github.com\jcansdale\GitPullRequest\GitPullRequest.Services\GitPullRequestService.cs:line 46
   at GitPullRequest.Program.<>c__DisplayClass21_0.<ListBranches>b__1(Branch b) in C:\Source\github.com\jcansdale\GitPullRequest\GitPullRequest\Program.cs:line 118
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at GitPullRequest.Program.ListBranches(GitPullRequestService service, Repository repo, String remoteName) in C:\Source\github.com\jcansdale\GitPullRequest\GitPullRequest\Program.cs:line 116
   at GitPullRequest.Program.OnExecute() in C:\Source\github.com\jcansdale\GitPullRequest\GitPullRequest\Program.cs:line 60
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 86
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 64
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass131_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 600
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 31
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 105
   at GitPullRequest.Program.Main(String[] args) in C:\Source\github.com\jcansdale\GitPullRequest\GitPullRequest\Program.cs:line 17
```

The attempted fix #30 wasn't quite right. 😢

**Comment by jcansdale** [comment]
Fixed by #35
