### ISSUE TITLE
Add support for bitbucket

### ISSUE THREAD

**Issue by propagated** [jcansdale/GitPullRequest#42]
Assuming this error message is accurate-
`System.NotSupportedException: Sorry, your git host is not supported!`

I work with a handful of repos on a private bitbucket server (currently on v5.15). Sadly i was unable to use the extension per this error.
```
System.NotSupportedException: Sorry, your git host is not supported!
   at GitPullRequest.Services.RemoteRepositoryFactory.Create(IRepository repo, String remoteName) in C:\Source\github.com\jcansdale\GitPullRequest\GitPullRequest.Services\RemoteRepositoryFactory.cs:line 31
   at GitPullRequest.Services.RemoteRepositoryCache.TryCreateRemoteRepository(String remoteName, RemoteRepository& remoteRepository) in C:\Source\github.com\jcansdale\GitPullRequest\GitPullRequest.Services\RemoteRepositoryCache.cs:line 40
Couldn't find pull request or remote branch
```

**Comment by jcansdale** [comment]
@propagated,

I'm afraid it is accurate at the moment.

I'd be interested to know what the output of `git ls-remote` is from one of your bitbucket repositories (with at least one open PR). Could you give that a try and let me know? 🙏

**Comment by propagated** [comment]
@jcansdale 
```
0a97cb0a3f4da47f8d1b89de91bb7bee477282a3	HEAD
97cc350dc81f1c9ba4d2e919debd5d2334b9996a	refs/heads/NGSS-399-convert-makeline-ui-files
0a97cb0a3f4da47f8d1b89de91bb7bee477282a3	refs/heads/develop
d7c64bd500dd7b3b6efcf9b3edda1fab99a5bbbe	refs/heads/feature/NGSS-183-automation-makeline-status
d7c64bd500dd7b3b6efcf9b3edda1fab99a5bbbe	refs/heads/feature/NGSS-184-automation-makeline-status-error
d7c64bd500dd7b3b6efcf9b3edda1fab99a5bbbe	refs/heads/feature/NGSS-185-automation-makeline-no-status
21ebc445b5f2d6f825dece29ff4d6ebfda6f09de	refs/heads/feature/NGSS-311-automation-makeline-persistence
55da76439c0f0cc4e3f61a2899e2678d9453b107	refs/heads/feature/NGSS-600_ML_Order_Pollingjob
ddd36eb3bcf018e3b4edc61de80a22de6eca4d75	refs/heads/feature/NGSS-601-revise-caching-repo
6833070db344de4f2e0b0b3e445ae3f90e972be0	refs/heads/feature/NGSS-602_refactor-caching-repository
9b66a40194bbcdbb4493bf4d57ad3d498cf5afcc	refs/heads/feature/UpdateLibraries
9ae8a287d26f0e8e9335acdb011c22249927cfdc	refs/heads/feature/bump-item
411c6ea8725450b951e87afa40d84c6dd8de69ba	refs/heads/feature/get-orders
5c511f3da74c9f6929b0d2bb23336fefb4986573	refs/heads/master
ddd36eb3bcf018e3b4edc61de80a22de6eca4d75	refs/pull-requests/48/from
6dcb84bf154b6b22bb34655bb75169546b86e355	refs/pull-requests/48/merge
6833070db344de4f2e0b0b3e445ae3f90e972be0	refs/pull-requests/50/from
37dbe0b21433f076173e042ce33e8c308f3c4376	refs/pull-requests/50/merge
```
Hope this helps 👍
